Setup Script Refactor

diff --git a/chameleon b/chameleon
--- a/chameleon
+++ b/chameleon
@@ -65,12 +65,56 @@ init()
 {
     lamp_installed
 
-    if [ $? -eq 0 ]; then
+    if [ $? -eq 1 ]; then
         echo "Installing required LAMP packages..."
         install_lamp_packages
     fi
 
     sudo a2enmod rewrite
+}
+
+
+#
+# Returns 0, if LAMP_PACKAGES are installed; 1 otherwise.
+#
+
+function lamp_installed
+{
+    local dpkg=/usr/bin/dpkg
+    
+    echo "Confirming LAMP installation..."
+
+    for package in $LAMP_PACKAGES; do
+        if [ $debug -gt 0 ]; then
+            echo "Verifing package: $package."
+        fi
+
+        $sudo $dpkg -s $package > /dev/null
+
+        if [ $? -eq 1 ]; then
+            return 1
+        fi
+    done
+
+    return 0
+}
+
+
+#
+# install_lamp_packages
+#
+
+function install_lamp_packages
+{
+    printf "Installing LAMP_PACKAGES... "
+
+    $sudo $aptget install -q=2 $LAMP_PACKAGES 
+
+    if [ $? -gt 0 ];then
+        echo "Installing LAMP_PACKAGES failed."
+    else
+        echo "Installing LAMP_PACKAGES successful."
+    fi
 }
 
 
@@ -124,7 +168,7 @@ composer()
 
 create_vhost()
 {
-    sudo bin/createVhost.php conf/apacheVirtualHost.txt
+    sudo bin/createVhost.php $vhost_template
 }
 
 
