Updated Setup with Required Linux Packages

diff --git a/chameleon b/chameleon
--- a/chameleon
+++ b/chameleon
@@ -1,4 +1,25 @@
 #!/bin/bash
+#
+# Chameleon
+# 
+# Copyright (C) 2016 Lakona Computers
+# 
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+# 
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+# @author Jason Favrod <jason@lakonacomputers.com>
+#
+
 source bin/chameleon-install.bash import
 CMD=$1
 
@@ -28,6 +49,7 @@ usage()
 
 setup()
 {
+    init
     index
     views
     config
@@ -35,6 +57,17 @@ setup()
     views
     composer
     perms
+}
+
+
+init()
+{
+    lamp_installed
+
+    if [ $? -eq 0 ]; then
+        echo "Installing required LAMP packages..."
+        install_lamp_packages
+    fi
 }
 
 
